"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

try:
    import dj_database_url
except ImportError:  # локальная разработка без полного requirements.txt
    dj_database_url = None

try:
    import whitenoise  # noqa: F401
    _has_whitenoise = True
except ImportError:
    _has_whitenoise = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_IS_VERCEL = bool(os.environ.get('VERCEL'))
_IS_RAILWAY = bool(
    os.environ.get('RAILWAY_ENVIRONMENT')
    or os.environ.get('RAILWAY_PROJECT_ID')
    or os.environ.get('RAILWAY_SERVICE_ID')
)


def _env_bool(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-@!d+_z98mxqdo4*othwc_4@c$*8g#_y_6x!ce22=s#=1w%6jq!',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

_allowed = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

_vercel_url = os.environ.get('VERCEL_URL', '').strip()
if _vercel_url and _vercel_url not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_vercel_url)
for _vercel_host in ('.vercel.app',):
    if _vercel_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_vercel_host)

if _IS_VERCEL:
    DEBUG = _env_bool('DJANGO_DEBUG', False)

if DEBUG:
    for _tunnel_host in ('.loca.lt', '.trycloudflare.com', '.ngrok-free.app'):
        if _tunnel_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_tunnel_host)

CSRF_TRUSTED_ORIGINS = []
for _origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(','):
    _origin = _origin.strip()
    if _origin:
        CSRF_TRUSTED_ORIGINS.append(_origin)
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_render_host}')
if _vercel_url:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_vercel_url}')

_railway_public = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '').strip()
if _railway_public and _railway_public not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_public)
for _railway_host in ('.railway.app', '.up.railway.app'):
    if _railway_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_railway_host)
if _railway_public:
    _railway_origin = f'https://{_railway_public}'
    if _railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_railway_origin)

if _IS_RAILWAY:
    DEBUG = _env_bool('DJANGO_DEBUG', False)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Railway сам передаёт Host; X-Forwarded-Host часто ломает проверку домена.
    if _env_bool('RAILWAY_USE_X_FORWARDED_HOST', False):
        USE_X_FORWARDED_HOST = True
    # Явный ALLOWED_HOSTS из панели (например .onrender.com) режет *.railway.app.
    if os.environ.get('ALLOWED_HOSTS', '').strip():
        ALLOWED_HOSTS = ['*']
    else:
        for _railway_exact in (
            'localhost',
            '127.0.0.1',
            'healthcheck.railway.app',
        ):
            if _railway_exact not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(_railway_exact)
        for _railway_suffix in ('.railway.internal', '.railway.app', '.up.railway.app'):
            if _railway_suffix not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(_railway_suffix)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vibel',
]

MIDDLEWARE = []
if _IS_VERCEL:
    MIDDLEWARE += [
        'vibel.middleware.SafeWriteErrorMiddleware',
        'vibel.middleware.VercelBootstrapMiddleware',
    ]
MIDDLEWARE += [
    'django.middleware.security.SecurityMiddleware',
]
if _has_whitenoise:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vibel.context_processors.header_state',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def _has_unresolved_railway_var(value) -> bool:
    return isinstance(value, str) and ('${{' in value or '}}' in value)


_db_url = os.environ.get('DATABASE_URL', '').strip()
if _has_unresolved_railway_var(_db_url):
    _db_url = ''
VERCEL_EPHEMERAL_DB = _IS_VERCEL and not _db_url


def _postgres_cfg_valid(cfg: dict) -> bool:
    engine = cfg.get('ENGINE', '')
    if 'postgresql' not in engine:
        return True
    for key in ('NAME', 'HOST', 'USER', 'PASSWORD'):
        if _has_unresolved_railway_var(cfg.get(key)):
            return False
    if cfg.get('NAME'):
        return True
    return bool((cfg.get('OPTIONS') or {}).get('service'))


_db_cfg = None
if _db_url and dj_database_url is not None:
    _parsed = dj_database_url.config(
        default=_db_url,
        conn_max_age=0 if _IS_VERCEL else 600,
    )
    if _postgres_cfg_valid(_parsed):
        _db_cfg = _parsed
        if _IS_VERCEL:
            _db_cfg.setdefault('OPTIONS', {})
            _db_cfg['OPTIONS'].setdefault('sslmode', 'require')
            _db_cfg['CONN_HEALTH_CHECKS'] = True
        elif _IS_RAILWAY and _db_url.startswith('postgres'):
            _db_cfg['CONN_HEALTH_CHECKS'] = True
            # Внутренняя сеть Railway (.railway.internal) — без принудительного SSL.
            if 'railway.internal' not in _db_url:
                _db_cfg.setdefault('OPTIONS', {})
                _db_cfg['OPTIONS'].setdefault('sslmode', 'require')

if _db_cfg is not None:
    DATABASES = {'default': _db_cfg}
elif _IS_RAILWAY:
    # Только build (collectstatic). На старте railway_preflight требует PostgreSQL.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif _IS_VERCEL:
    # На Vercel файловая система проекта read-only — пишем в /tmp.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/tmp/vibelog.db',
        }
    }
elif dj_database_url is not None:
    DATABASES = {
        'default': dj_database_url.config(
            default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('ru', 'Русский'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
if _IS_VERCEL:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    if _has_whitenoise:
        # Исходники vibel/static/ уже в репозитории — отдаём без collectstatic на CDN.
        WHITENOISE_USE_FINDERS = True
        WHITENOISE_AUTOREFRESH = False
elif _has_whitenoise and (
    _env_bool('BEGET_DEPLOY', False) or _IS_RAILWAY or not DEBUG
):
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = '/media/'
if _IS_VERCEL:
    MEDIA_ROOT = Path('/tmp/media')
    SERVE_MEDIA = True
elif _IS_RAILWAY:
    # Подключите Volume в Railway на этот путь — фото/видео сохранятся после redeploy.
    MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))
    SERVE_MEDIA = _env_bool('SERVE_MEDIA', True)
else:
    MEDIA_ROOT = BASE_DIR / 'media'
    SERVE_MEDIA = _env_bool('SERVE_MEDIA', DEBUG)

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

if _IS_VERCEL:
    # Без внешней БД данные в /tmp живут только до cold start.
    SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 дней
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    if VERCEL_EPHEMERAL_DB:
        # Сессия в подписанной cookie — меньше зависимость от sqlite в /tmp.
        SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
    for _host in ALLOWED_HOSTS:
        if _host.startswith('.'):
            continue
        _origin = f'https://{_host}'
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

# На Vercel лимит тела запроса ~4.5 МБ; на Railway — полные лимиты.
if _IS_VERCEL:
    MAX_IMAGE_UPLOAD_BYTES = 3 * 1024 * 1024
    MAX_VIDEO_UPLOAD_BYTES = 3 * 1024 * 1024
else:
    MAX_IMAGE_UPLOAD_BYTES = 8 * 1024 * 1024
    MAX_VIDEO_UPLOAD_BYTES = 50 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = max(MAX_IMAGE_UPLOAD_BYTES, MAX_VIDEO_UPLOAD_BYTES) + (1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
