# Generated by Django 4.2.29 on 2026-04-04 06:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vibel', '0003_savedpost_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_overlay',
            field=models.PositiveSmallIntegerField(default=72, help_text='Чем выше — тем плотнее «вуаль» поверх фото, лучше читается текст.', verbose_name='затемнение фона (читаемость), %'),
        ),
        migrations.AddField(
            model_name='profile',
            name='page_background',
            field=models.ImageField(blank=True, null=True, upload_to='page_bg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='фон страницы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=8, verbose_name='тема'),
        ),
        migrations.CreateModel(
            name='AppearanceCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Чекпоинт', max_length=80, verbose_name='название')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], max_length=8)),
                ('background_overlay', models.PositiveSmallIntegerField()),
                ('snapshot_background', models.ImageField(blank=True, null=True, upload_to='checkpoint_bg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'чекпоинт оформления',
                'verbose_name_plural': 'чекпоинты оформления',
                'ordering': ['-created_at'],
            },
        ),
    ]
