# Generated by Django 4.2.29 on 2026-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibel', '0004_profile_background_overlay_profile_page_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_overlay',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='page_background',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='обложка'),
        ),
        migrations.DeleteModel(
            name='AppearanceCheckpoint',
        ),
    ]
